"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO: Ganti SECRET_KEY saat production!
SECRET_KEY = 'django-insecure-&-32_kttuq4yja1x&)5iw&ir(@5vf^*i1u55vr98axlt7ybs=s'

# SECURITY WARNING: don't run with debug turned on in production!
# TODO: Set DEBUG = False saat deploy production
DEBUG = True

ALLOWED_HOSTS = ['4d90-114-10-98-222.ngrok-free.app', '127.0.0.1', 'localhost']

# Data Upload Settings - untuk bulk operations di admin
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Default: 1000, dinaikkan untuk bulk delete banyak data
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB (untuk upload file)

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Django Jazzmin - Harus di atas django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Untuk format angka
    'users',
    'dashboard',  
    'prediction',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'prediksi_db',     # Nama database Anda sudah benar
        'USER': 'root',           # COBA GUNAKAN INI
        'PASSWORD': '',           # KOSONGKAN PASSWORDNYA
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Daftar direktori tempat Django akan mencari file statis
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'users/static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# PENGATURAN UNTUK FILE UPLOAD (MEDIA)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# DJANGO JAZZMIN CONFIGURATION
# ==========================================

JAZZMIN_SETTINGS = {
    # Judul aplikasi di halaman login dan header
    "site_title": "Pregamo - Admin",
    
    # Judul di header admin
    "site_header": "Sistem Prediksi Harga Mobil Bekas",
    
    # Teks brand di sidebar (tidak menggunakan logo gambar)
    "site_brand": "Pregamo - Admin",
    
    # Logo di halaman login (kosongkan karena hanya menggunakan teks)
    "site_logo": None,
    
    # Logo di sidebar (kosongkan juga)
    "login_logo": None,
    
    # Classes untuk logo
    "site_logo_classes": "img-circle",
    
    # Icon logo (menggunakan FontAwesome star icon)
    "site_icon": "fas fa-star",
    
    # Pesan sambutan di halaman admin (Bahasa Indonesia)
    "welcome_sign": "Selamat Datang di Panel Admin",
    
    # Copyright footer (Bahasa Indonesia)
    "copyright": "Pregamo © 2026",
    
    # Pencarian model di sidebar
    "search_model": ["auth.User", "prediction.CarDataset", "prediction.PredictionHistory"],
    
    # User avatar (tidak menggunakan avatar)
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Link tambahan di top menu (bisa dikosongkan)
    "topmenu_links": [
        # Link ke home admin
        {"name": "Beranda", "url": "admin:index", "permissions": ["auth.view_user"]},
        
        # Link ke aplikasi utama (opsional, sesuaikan dengan URL Anda)
        {"name": "Lihat Situs", "url": "/", "new_window": True},
    ],
    
    #############
    # Side Menu #
    #############
    
    # Tampilkan permissions di sidebar
    "show_sidebar": True,
    
    # Navigasi diperluas secara default (False agar lebih rapi)
    "navigation_expanded": False,
    
    # Sembunyikan aplikasi yang tidak diinginkan
    "hide_apps": ["users", "dashboard"],
    
    # Sembunyikan model tertentu (kosongkan untuk menampilkan semua)
    "hide_models": [],
    
    # Warna sidebar (light untuk tema terang)
    "sidebar_classes": "sidebar-light-primary elevation-2",
    
    # Urutan aplikasi di sidebar (Prediction di paling atas)
    "order_with_respect_to": ["prediction", "auth", "users", "dashboard"],
    
    # Custom links untuk setiap aplikasi di menu
    "custom_links": {},
    
    # Icons untuk setiap aplikasi dan model (FontAwesome)
    "icons": {
        # Icons untuk auth app
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Icons untuk aplikasi Prediction
        "prediction": "fas fa-chart-line",
        "prediction.CarDataset": "fas fa-car",
        "prediction.PredictionHistory": "fas fa-history",
        "prediction.Brand": "fas fa-tags",
        
        # Icons untuk aplikasi lain (opsional)
        "users": "fas fa-user-circle",
        "dashboard": "fas fa-tachometer-alt",
    },
    
    # Default icon fallback
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # Related Modal #
    #################
    
    # Gunakan modal untuk related objects
    "related_modal_active": False,
    
    #############
    # UI Tweaks #
    #############
    
    # Custom CSS untuk styling tambahan
    "custom_css": "css/admin/custom_admin.css",
    
    # Custom JS (kosongkan jika tidak ada)
    "custom_js": None,
    
    # Gunakan Google Font
    "use_google_fonts_cdn": True,
    
    # Tampilkan UI Customizer (bisa dimatikan di production)
    "show_ui_builder": False,
    
    ###############
    # Change view #
    ###############
    
    # Tampilkan carousel di change form
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# ==========================================
# JAZZMIN UI TWEAKS (TEMA & STYLING)
# ==========================================

JAZZMIN_UI_TWEAKS = {
    # Tema light yang cerah dengan kontras tinggi - cosmo lebih terang dari flatly
    "theme": "cosmo",
    
    # Matikan dark mode
    "dark_mode_theme": None,
    
    # Navbar styling - navbar putih terang
    "navbar": "navbar-white navbar-light",
    "navbar_fixed": True,
    
    # Sidebar styling - light mode dengan kontras lebih baik
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,  # Compact untuk lebih rapi
    "sidebar_nav_legacy": False,
    "sidebar_nav_flat_style": True,
    
    # Brand styling - putih terang
    "brand_small_text": False,
    "brand_color": "navbar-white",
    
    # Layout spacing
    "layout_boxed": False,
    "footer_fixed": False,
    "body_small_text": False,
    
    # Font - gunakan system font yang lebih jelas
    "font_family": '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
    
    # Button styles - lebih jelas dan terang
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    
    # Action button styles
    "actions_sticky_top": True,
}

